Add scc validator

diff --git a/build/cloudbuild-tf-apply.yaml b/build/cloudbuild-tf-apply.yaml
--- a/build/cloudbuild-tf-apply.yaml
+++ b/build/cloudbuild-tf-apply.yaml
@@ -15,6 +15,12 @@
 timeout: 3600s
 substitutions:
   _POLICY_REPO: '/workspace/policy-library' # add path to policies here https://github.com/forseti-security/policy-library/blob/master/docs/user_guide.md#how-to-use-terraform-validator
+  _LOGGER_NAME: scc_logging_test # default value
+  _CRITICAL: "0" # default value
+  _HIGH: "50" # default value
+  _MEDIUM: "50" # default value
+  _FUNCTION_NAME: "scc_helper_updated"
+  _SCOPED_PROJECT: "prj-b-cicd-91a1"
 
 steps:
 - id: 'setup'
@@ -68,6 +74,26 @@ steps:
       echo "Setting up gcloud for impersonation ${tf_sa_email}"
       ./tf-wrapper.sh apply ${BRANCH_NAME}
 
+- id: 'Secure Command Center validator'
+  name: 'gcr.io/cloud-builders/gcloud'
+  entrypoint: 'bash'
+  waitFor: 
+  - 'tf apply' 
+  args:
+  - 'sleep 120'
+  - '-c'
+  - |-
+    output=$(gcloud functions call ${_FUNCTION_NAME} --data '{"logger_name":"$_LOGGER_NAME", "scoped_project": "$_SCOPED_PROJECT", "critical_max": $_CRITICAL, "high_max": $_HIGH, "medium_max": $_MEDIUM }')
+    if [[ "$output" == *"Error"* ]] 
+    then
+        gcloud logging read "logName=projects/${PROJECT_ID}/logs/${_LOGGER_NAME}" 
+        echo "Build Failed"
+        exit 1
+    else
+        gcloud logging read "logName=projects/${PROJECT_ID}/logs/${_LOGGER_NAME}" 
+        echo "Build Passed"
+        
+    fi
  
 artifacts:
   objects:
